
/* -------------------------------------------------------------------
   Code generated by SAS Task

   Generated on: Thursday, January 08, 2015 at 9:46:50 AM
   By task: Data Set Attributes2

   Input Data: Local:MYDATA.18OVRVARIABLES
   Server:  Local
   ------------------------------------------------------------------- */

%_eg_conditional_dropds(MYDATA.CONTCONTENTSFOR18OVRVARIABLES);
TITLE "Data set attributes for subset data set";
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";

PROC DATASETS NOLIST NODETAILS; 
   CONTENTS DATA=MYDATA.'18OVRVARIABLES'n ;

RUN;


